### ISSUE TITLE
Steam OS 3.5 Preview - Unable to select device

### ISSUE THREAD

**Issue by rockjob** [Outpox/Bluetooth#10]
Steam OS build: 20230915.100
Kernel Version: 6.1.52-valve2-1-neptune-61
Decky Version: 2.10.4
Bluetooth plugin Version: 2.0.4

Issue:

- In bluetooth plugin: Was unable to move cursor down from bluetooth toggle. Refresh bluetooth devices and 2 paired devices were visible, but cursor was stuck on bluetooth toggle. Could go up to decky back button.
- Tried forgetting the devices in steam bluetooth menu. Re-paired one device. Went back to bluetooth decky and paired device is not visible. (Only bluetooth toggle and "bluetooth devices" refresh item is there but cursor will only go between toggle and back button)

Edit:
Tried on decky prerelease version v2.10.5-pre2. Same issue.

**Comment by Outpox** [comment]
Thanks for raising an issue. It was already brought to my attention a month ago and I tried to reproduce it without success.   
I'm unavailable this week but I'll set up a reminder and will try to have another go next week.

**Comment by rockjob** [comment]
Let me know if I can help. Pulling logs or installing a dev build with more logging.

**Comment by Outpox** [comment]
If you can access the logs they would most likely be helpful and I don't have a dev build with more logging.

**Comment by Outpox** [comment]
I've just noticed the [latest release](https://github.com/Outpox/Bluetooth/issues/9) `v.2.1.0` which should fix the issue you're facing isn't available on the store and only `v.2.0.4` is.  
While I'm looking to resolve this issue, if you want to give it a try early you can manually install it by following these steps:  
* Download the release build I just uploaded on the release page: https://github.com/Outpox/Bluetooth/releases/tag/v2.1.0
  * Make sure to only download `Bluetooth-2.1.0.zip` and NOT `source code`
  * You can do this via the browser in gaming or desktop mode
* In Decky setting menu:
* Uninstall `v.2.0.4` via the plugins tab
* In the developer tab
  * Click on `Browse` next to `Install Plugin from ZIP File` and select the file you downloaded: `Bluetooth-2.1.0.zip`
  * It should be in the Download folder I believe  
* The UI should refresh and the plugin won't show initially
* To refresh the view you can either
  * Restart your deck
  * Go to desktop and back to gaming mode
  * Or change decky channel from stable to prerelease and install the update (or vice-versa)  
  
  
Let me know if it fixes your issue  
  

![image](https://github.com/Outpox/Bluetooth/assets/3439246/3f36af55-8147-4a49-a7dd-8ecd82be7bcf)

**Comment by Outpox** [comment]
The issue on the store side has been resolved, the plugin is now available there in `v2.1.0` and you needn't install it manually anymore.  
I've been told it fixed the issue in SteamOS 3.5 so I'll be closing this issue, if you have another problem I'll reopen it 👍
