### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by Fethbita** [Outpox/Bluetooth#12]
I get an error while trying to click on the Bluetooth plugin on Steam Deck OS 3.5.19, Decky version 2.12.3 and plugin version 2.2.0. I get the following error in full screen:
```
Error reference: Shared SteamUI_8971085_83e9fb24b6fb3c75
Cannot read properties of undefined (reading 'RegisterForStateChanges')
```

I tried uninstalling the plugin but it didn't work. I haven't used my Deck in a while, so I picked it up after not turning it on for many months, and I am not sure if the issue is only on my side or if it is general.

**Comment by benbc7** [comment]
I'm getting the same error. It was working fine earlier today before I updated. I think the only thing that updated for me today was the steam client version, which updated to version 1718305227.

**Comment by Outpox** [comment]
The last steamOS update broke the plugin and there isn't much I can do
about it at the moment.
The update also includes the plugin functionality natively, have a look
into the native menu.

**Comment by Fofer** [comment]
>The update also includes the plugin functionality natively

What I liked most about this plugin is that it reported the battery percentage of connected Bluetooth accessories, including my headphones, controller and mini travel keyboard, quickly whilst in Game mode.  As far as I can tell the SteamOS update doesn't include that information unfortunately.  I'd love to see this handy plugin return, if possible.  Thanks so much for making it in the first place!

**Comment by benbc7** [comment]
I like to connect my phone or linux laptop to my deck via bluetooth to send audio to the headphones on the deck, or the other way around. For whatever reason, android and linux devices only show up in bluetooth settings on the deck if you toggle on "other devices," which also means they don't show up in the new native QAM bluetooth device list. Really missing the plugin now cause I have to go into settings to manage any of that.

**Comment by Outpox** [comment]
Thanks for the feedback, I understand there is still a need for the plugin.  
I had a look when I received the first report that it stopped working and the issue is that the SteamOS functions that I used to manage bluetooth have been removed (hence why the plugin fails on startup now). Either they restore it later and it'll be easier for me or I'll have to resort to manage bluetooth with bluez like I did in the first versions of the plugin.  
I'm leaving on holidays today so I won't have time now but I'll work on it when I can.  
Thanks again for your support ✌️

**Comment by introkun** [comment]
Subscribed since I have save issue

**Comment by introkun** [comment]
I've provided a workaround and tested it with my Sony 1000XM4. Bluetooth toggle will not work, but the plugin is loaded and can connect/disconnect devices.

**Comment by SiTWulf** [comment]
> The update also includes the plugin functionality natively, have a look into the native menu. 
I cant see it.
You can please show me a screenshot with this native feature?

**Comment by Outpox** [comment]
Plugin update is awaiting review https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/659

**Comment by Outpox** [comment]
Plugin update is now live, enjoy!
