### ISSUE TITLE
Set state of all devices to disconnected on sleep

### ISSUE THREAD

**Issue by keineahnungking** [Outpox/Bluetooth#4]
In the May 16th release version whenever I put the Steam deck to sleep with a device connected and wake it up again the plugin shows the device as connected still even though it has been disconnected. This leads to the process of connecting it again taking twice as long because I have to click on it, wait for it to show disconnected and then click again to connect. This might have been already fixed in the upcoming release but I just wanted to write this in case it wasn't.

**Comment by Outpox** [comment]
I don't know if it fixable but as a workaround you can simply refresh the devices list or exit the bluetooth menu and get back in.  
In the legacy version there was no way to know when the menu is focused or not so I couldn't auto-update the list (and I tried), this might be the same with the new frontend.
