### ISSUE TITLE
Feature Request: Bluetooth Toggle

### ISSUE THREAD

**Issue by Richm246** [Outpox/Bluetooth#6]
I am wondering if it is possible to have a toggle for Bluetooth to be enabled/disabled.

**Comment by Outpox** [comment]
It is already possible in the new [settings-menu](https://github.com/Outpox/Bluetooth/tree/settings-menu) branch however it's still in progress and not released on the plugin store.  
I haven't worked on it lately but if you can install it manually it should work.

**Comment by Richm246** [comment]
I'll wait for it to be in the plugin store, thanks 👍
